Optimize query to prevent notification from mongo db
futureversecom/trn-block-explorer pull request #106
Opened 2023-11-24 10:40 UTC by KarishmaBothara

## Summary

Break look_up query and have two mongo api calls to get data from different collection instead of using join.

## Checklist

- [x] Add description

2023-11-29 04:26 UTC, ken-centrality requested changes

2023-11-29 04:26 UTC, ken-centrality commented on components/erc20TransfersForAddress.js
> +			refetchInterval: 85_000,
the `refetchInterval` here is different to the one in `queryTxs`,  are we running into the risk of it's being out of sync?

2023-11-29 04:26 UTC, ken-centrality commented on components/evmTransactionsWidget.js
> +	console.log("Query....", query);
```suggestion
```

2023-11-29 04:26 UTC, ken-centrality commented on pages/api/evm/getERC20TransferForAddress.ts
> +					// {
remove commented code

2023-11-29 04:26 UTC, ken-centrality commented on pages/api/evm/getERC721TransferForAddress.ts
> +					// {
remove commented code

2023-11-29 04:26 UTC, ken-centrality commented on pages/api/evm/getEVMTransactions.ts
> +					// {
remove commented code

2023-11-29 04:26 UTC, ken-centrality commented on libs/evm-api/index.js
> +export const getContractDataForAddresses = async (addresses) => {
this is not used anywhere

2023-11-29 04:26 UTC, ken-centrality commented on pages/api/evm/getContractDataForAddresses.ts
not used anywhere

2023-11-29 11:11 UTC, KarishmaBothara commented on components/erc20TransfersForAddress.js
> +			refetchInterval: 85_000,
This query gets the contract details.. if it exist so I made it refetch after 85_000 seconds.. cause most of the time data received from here would be null

2023-11-29 11:17 UTC, KarishmaBothara commented on libs/evm-api/index.js
> +export const getContractDataForAddresses = async (addresses) => {
will check this..

2023-11-29 11:31 UTC, KarishmaBothara commented on pages/api/evm/getContractDataForAddresses.ts
same as above

2023-12-01 02:54 UTC, ken-centrality approved these changes

2023-12-01 02:55 UTC, ken-centrality approved these changes

2023-12-01 02:55 UTC, merged